language: en
autodownload: true
installondownload: false
updateCheck: true
senderrorreport: true
senddebugfile: false
debug: false
debugfile: true
users_can_choose_privacy: false
UsePrefix: true
Prefix: CurveCraft
PrefixColor: b
TextColor: 6
updateIntervall: 30
everyArenaOwnJoinPermission: false
globalcommandwhitelist: false